channels:
  - conda-forge
dependencies:
  # Core
  - ipykernel
  - ipywidgets
  - pip
  - python=3.10
  # Data tools
  - dask
  - intake
  - intake-xarray
  - pooch
  - xarray
  - zarr
  # Visualisation
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - panel
  - pyvista
  - trame
  # Build
  - jupyter-book
  # Domain-specific
  - pip:
    - chaosmagpy
